-- MySQL Script generated by MySQL Workbench
-- lun 26 sep 2016 11:34:26 CLST
-- Model: SGD Modules    Version: 1.0

-- Modelos relacionales modulos:
-- "Sistema gestion de desemepeño"

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgd-modules
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgd-modules
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgd-modules` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `sgd-modules` ;

-- -----------------------------------------------------
-- Table `sgd-modules`.`version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`version` (
  `idversion` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `numero` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idversion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`entidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`entidad` (
  `identidad` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `idrelacionEntidad` INT NOT NULL,
  PRIMARY KEY (`identidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`componente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`componente` (
  `idcomponente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `idrelacionComponente` INT NOT NULL,
  PRIMARY KEY (`idcomponente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`entidad_has_componente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`entidad_has_componente` (
  `entidad_identidad` INT NOT NULL,
  `componente_idcomponente` INT NOT NULL,
  PRIMARY KEY (`entidad_identidad`, `componente_idcomponente`),
  INDEX `fk_entidad_has_componente_componente1_idx` (`componente_idcomponente` ASC),
  INDEX `fk_entidad_has_componente_entidad1_idx` (`entidad_identidad` ASC),
  CONSTRAINT `fk_entidad_has_componente_entidad1`
    FOREIGN KEY (`entidad_identidad`)
    REFERENCES `sgd-modules`.`entidad` (`identidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entidad_has_componente_componente1`
    FOREIGN KEY (`componente_idcomponente`)
    REFERENCES `sgd-modules`.`componente` (`idcomponente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`entidad_has_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`entidad_has_version` (
  `entidad_identidad` INT NOT NULL,
  `version_idversion` INT NOT NULL,
  PRIMARY KEY (`entidad_identidad`, `version_idversion`),
  INDEX `fk_entidad_has_version_version1_idx` (`version_idversion` ASC),
  INDEX `fk_entidad_has_version_entidad1_idx` (`entidad_identidad` ASC),
  CONSTRAINT `fk_entidad_has_version_entidad1`
    FOREIGN KEY (`entidad_identidad`)
    REFERENCES `sgd-modules`.`entidad` (`identidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entidad_has_version_version1`
    FOREIGN KEY (`version_idversion`)
    REFERENCES `sgd-modules`.`version` (`idversion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`componente_has_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`componente_has_version` (
  `componente_idcomponente` INT NOT NULL,
  `version_idversion` INT NOT NULL,
  PRIMARY KEY (`componente_idcomponente`, `version_idversion`),
  INDEX `fk_componente_has_version_version1_idx` (`version_idversion` ASC),
  INDEX `fk_componente_has_version_componente1_idx` (`componente_idcomponente` ASC),
  CONSTRAINT `fk_componente_has_version_componente1`
    FOREIGN KEY (`componente_idcomponente`)
    REFERENCES `sgd-modules`.`componente` (`idcomponente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_componente_has_version_version1`
    FOREIGN KEY (`version_idversion`)
    REFERENCES `sgd-modules`.`version` (`idversion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
