-- MySQL Script generated by MySQL Workbench
-- jue 15 sep 2016 10:40:26 CLST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgd-modules
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgd-modules
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgd-modules` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `sgd-modules` ;

-- -----------------------------------------------------
-- Table `sgd-modules`.`versionEscala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`versionEscala` (
  `idversionEscala` INT NOT NULL,
  `tag` VARCHAR(5) NOT NULL,
  `fechaCreacion` DATE NOT NULL,
  PRIMARY KEY (`idversionEscala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`escala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`escala` (
  `idescala` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `versionEscala_idversionEscala` INT NOT NULL,
  PRIMARY KEY (`idescala`),
  INDEX `fk_escala_versionEscala1_idx` (`versionEscala_idversionEscala` ASC),
  CONSTRAINT `fk_escala_versionEscala1`
    FOREIGN KEY (`versionEscala_idversionEscala`)
    REFERENCES `sgd-modules`.`versionEscala` (`idversionEscala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`eslabon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`eslabon` (
  `ideslabon` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `valor` INT NOT NULL,
  PRIMARY KEY (`ideslabon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`escala_has_eslabon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`escala_has_eslabon` (
  `escala_idescala` INT NOT NULL,
  `eslabon_ideslabon` INT NOT NULL,
  PRIMARY KEY (`escala_idescala`, `eslabon_ideslabon`),
  INDEX `fk_escala_has_eslabon_eslabon1_idx` (`eslabon_ideslabon` ASC),
  INDEX `fk_escala_has_eslabon_escala1_idx` (`escala_idescala` ASC),
  CONSTRAINT `fk_escala_has_eslabon_escala1`
    FOREIGN KEY (`escala_idescala`)
    REFERENCES `sgd-modules`.`escala` (`idescala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escala_has_eslabon_eslabon1`
    FOREIGN KEY (`eslabon_ideslabon`)
    REFERENCES `sgd-modules`.`eslabon` (`ideslabon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
