-- MySQL Script generated by MySQL Workbench
-- jue 15 sep 2016 12:46:30 CLST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgd-modules
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgd-modules
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgd-modules` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `sgd-modules` ;

-- -----------------------------------------------------
-- Table `sgd-modules`.`enlace`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`enlace` (
  `idenlace` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `idcomponente` INT NOT NULL,
  PRIMARY KEY (`idenlace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`ponderacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`ponderacion` (
  `idponderacion` INT NOT NULL,
  `porcentaje` VARCHAR(45) NOT NULL,
  `fechaCreacion` DATE NULL,
  `enlace_idenlace` INT NOT NULL,
  PRIMARY KEY (`idponderacion`, `enlace_idenlace`),
  INDEX `fk_ponderacion_enlace1_idx` (`enlace_idenlace` ASC),
  CONSTRAINT `fk_ponderacion_enlace1`
    FOREIGN KEY (`enlace_idenlace`)
    REFERENCES `sgd-modules`.`enlace` (`idenlace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`nodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`nodo` (
  `idnodo` INT NOT NULL,
  `ponderacion_idponderacion` INT NOT NULL,
  `nivel` INT NOT NULL,
  PRIMARY KEY (`idnodo`),
  INDEX `fk_nodo_ponderacion1_idx` (`ponderacion_idponderacion` ASC),
  CONSTRAINT `fk_nodo_ponderacion1`
    FOREIGN KEY (`ponderacion_idponderacion`)
    REFERENCES `sgd-modules`.`ponderacion` (`idponderacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
