-- MySQL Script generated by MySQL Workbench
-- lun 26 sep 2016 10:33:51 CLST
-- Model: SGD Modules    Version: 1.0

-- Modelos relacionales modulos:
-- "Sistema gestion de desemepeño"

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgd-modules
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgd-modules
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgd-modules` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `sgd-modules` ;

-- -----------------------------------------------------
-- Table `sgd-modules`.`evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`evaluacion` (
  `idevaluacion` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `fechaCreacion` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `angulo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idevaluacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`formulario` (
  `idformulario` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `bloque` INT NOT NULL,
  PRIMARY KEY (`idformulario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`pregunta` (
  `idpregunta` INT NOT NULL,
  `texto` LONGTEXT NULL,
  PRIMARY KEY (`idpregunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`formulario_has_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`formulario_has_pregunta` (
  `formulario_idformulario` INT NOT NULL,
  `pregunta_idpregunta` INT NOT NULL,
  PRIMARY KEY (`formulario_idformulario`, `pregunta_idpregunta`),
  INDEX `fk_formulario_has_pregunta_pregunta1_idx` (`pregunta_idpregunta` ASC),
  INDEX `fk_formulario_has_pregunta_formulario1_idx` (`formulario_idformulario` ASC),
  CONSTRAINT `fk_formulario_has_pregunta_formulario1`
    FOREIGN KEY (`formulario_idformulario`)
    REFERENCES `sgd-modules`.`formulario` (`idformulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_formulario_has_pregunta_pregunta1`
    FOREIGN KEY (`pregunta_idpregunta`)
    REFERENCES `sgd-modules`.`pregunta` (`idpregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`evaluacion_has_formulario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`evaluacion_has_formulario` (
  `evaluacion_idevaluacion` INT NOT NULL,
  `formulario_idformulario` INT NOT NULL,
  PRIMARY KEY (`evaluacion_idevaluacion`, `formulario_idformulario`),
  INDEX `fk_evaluacion_has_formulario_formulario1_idx` (`formulario_idformulario` ASC),
  INDEX `fk_evaluacion_has_formulario_evaluacion1_idx` (`evaluacion_idevaluacion` ASC),
  CONSTRAINT `fk_evaluacion_has_formulario_evaluacion1`
    FOREIGN KEY (`evaluacion_idevaluacion`)
    REFERENCES `sgd-modules`.`evaluacion` (`idevaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_has_formulario_formulario1`
    FOREIGN KEY (`formulario_idformulario`)
    REFERENCES `sgd-modules`.`formulario` (`idformulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
