-- MySQL Script generated by MySQL Workbench
-- lun 26 sep 2016 11:24:47 CLST
-- Model: SGD Modules    Version: 1.0

-- Modelos relacionales modulos:
-- "Sistema gestion de desemepeño"

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgd-modules
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgd-modules
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgd-modules` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `sgd-modules` ;

-- -----------------------------------------------------
-- Table `sgd-modules`.`evaluado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`evaluado` (
  `idevaluado` INT NOT NULL,
  `idaudiencia` INT NOT NULL,
  PRIMARY KEY (`idevaluado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`evaluador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`evaluador` (
  `idevaluador` INT NOT NULL,
  `idaudiencia` INT NOT NULL,
  `tipoRelacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idevaluador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`evaluador_has_evaluado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`evaluador_has_evaluado` (
  `evaluador_idevaluador` INT NOT NULL,
  `evaluado_idevaluado` INT NOT NULL,
  PRIMARY KEY (`evaluador_idevaluador`, `evaluado_idevaluado`),
  INDEX `fk_evaluador_has_evaluado_evaluado1_idx` (`evaluado_idevaluado` ASC),
  INDEX `fk_evaluador_has_evaluado_evaluador1_idx` (`evaluador_idevaluador` ASC),
  CONSTRAINT `fk_evaluador_has_evaluado_evaluador1`
    FOREIGN KEY (`evaluador_idevaluador`)
    REFERENCES `sgd-modules`.`evaluador` (`idevaluador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluador_has_evaluado_evaluado1`
    FOREIGN KEY (`evaluado_idevaluado`)
    REFERENCES `sgd-modules`.`evaluado` (`idevaluado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
