-- MySQL Script generated by MySQL Workbench
-- mar 13 sep 2016 11:01:00 CLST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgd-modules
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgd-modules
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgd-modules` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `sgd-modules` ;

-- -----------------------------------------------------
-- Table `sgd-modules`.`competencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`competencia` (
  `idCompetencia` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `fechaCreacion` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCompetencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`version` (
  `idVersion` INT NOT NULL,
  `fechaInicio` VARCHAR(45) NOT NULL,
  `fechaFin` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `idCompetencia` INT NOT NULL,
  PRIMARY KEY (`idVersion`),
  INDEX `fk_version_1_idx` (`idCompetencia` ASC),
  CONSTRAINT `fk_version_1`
    FOREIGN KEY (`idCompetencia`)
    REFERENCES `sgd-modules`.`competencia` (`idCompetencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`actividadClave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`actividadClave` (
  `idactividadClave` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idactividadClave`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`criterioDesempeno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`criterioDesempeno` (
  `idcriterioDesempeno` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `idactividadClave` INT NULL,
  PRIMARY KEY (`idcriterioDesempeno`),
  INDEX `fk_criterioDesempeno_1_idx` (`idactividadClave` ASC),
  CONSTRAINT `fk_criterioDesempeno_1`
    FOREIGN KEY (`idactividadClave`)
    REFERENCES `sgd-modules`.`actividadClave` (`idactividadClave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`indicadorConducta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`indicadorConducta` (
  `idindicadorConducta` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idindicadorConducta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`especializacionCompetencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`especializacionCompetencia` (
  `idespecializacionCompetencia` INT NOT NULL,
  `idCompetencia` INT NOT NULL,
  `idtipoEspecializacion` INT NULL,
  PRIMARY KEY (`idespecializacionCompetencia`),
  INDEX `fk_especializacionCompetencia_1_idx` (`idtipoEspecializacion` ASC),
  INDEX `fk_especializacionCompetencia_3_idx` (`idCompetencia` ASC),
  CONSTRAINT `fk_especializacionCompetencia_1`
    FOREIGN KEY (`idtipoEspecializacion`)
    REFERENCES `sgd-modules`.`actividadClave` (`idactividadClave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_especializacionCompetencia_2`
    FOREIGN KEY (`idtipoEspecializacion`)
    REFERENCES `sgd-modules`.`indicadorConducta` (`idindicadorConducta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_especializacionCompetencia_3`
    FOREIGN KEY (`idCompetencia`)
    REFERENCES `sgd-modules`.`competencia` (`idCompetencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
