-- MySQL Script generated by MySQL Workbench
-- mié 14 sep 2016 17:25:08 CLST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sgd-modules
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgd-modules
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgd-modules` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `sgd-modules` ;

-- -----------------------------------------------------
-- Table `sgd-modules`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`periodo` (
  `idperiodo` INT NOT NULL,
  `fechaInicio` VARCHAR(45) NULL,
  `fechaFin` VARCHAR(45) NULL,
  PRIMARY KEY (`idperiodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`proceso` (
  `idproceso` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `periodo_idperiodo` INT NOT NULL,
  PRIMARY KEY (`idproceso`),
  INDEX `fk_proceso_periodo1_idx` (`periodo_idperiodo` ASC),
  CONSTRAINT `fk_proceso_periodo1`
    FOREIGN KEY (`periodo_idperiodo`)
    REFERENCES `sgd-modules`.`periodo` (`idperiodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`extension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`extension` (
  `idextension` INT NOT NULL,
  `fechaInicio` VARCHAR(45) NULL,
  `fechaFin` VARCHAR(45) NULL,
  PRIMARY KEY (`idextension`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`subProceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`subProceso` (
  `idsubproceso` INT NOT NULL,
  `idModulo` INT NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  PRIMARY KEY (`idsubproceso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`proceso_has_subProceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`proceso_has_subProceso` (
  `proceso_idproceso` INT NOT NULL,
  `subProceso_idsubproceso` INT NOT NULL,
  PRIMARY KEY (`proceso_idproceso`, `subProceso_idsubproceso`),
  INDEX `fk_proceso_has_subProceso_subProceso1_idx` (`subProceso_idsubproceso` ASC),
  INDEX `fk_proceso_has_subProceso_proceso1_idx` (`proceso_idproceso` ASC),
  CONSTRAINT `fk_proceso_has_subProceso_proceso1`
    FOREIGN KEY (`proceso_idproceso`)
    REFERENCES `sgd-modules`.`proceso` (`idproceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proceso_has_subProceso_subProceso1`
    FOREIGN KEY (`subProceso_idsubproceso`)
    REFERENCES `sgd-modules`.`subProceso` (`idsubproceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`periodo_has_extension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`periodo_has_extension` (
  `periodo_idperiodo` INT NOT NULL,
  `extension_idextension` INT NOT NULL,
  PRIMARY KEY (`periodo_idperiodo`, `extension_idextension`),
  INDEX `fk_periodo_has_extension_extension1_idx` (`extension_idextension` ASC),
  INDEX `fk_periodo_has_extension_periodo1_idx` (`periodo_idperiodo` ASC),
  CONSTRAINT `fk_periodo_has_extension_periodo1`
    FOREIGN KEY (`periodo_idperiodo`)
    REFERENCES `sgd-modules`.`periodo` (`idperiodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_periodo_has_extension_extension1`
    FOREIGN KEY (`extension_idextension`)
    REFERENCES `sgd-modules`.`extension` (`idextension`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgd-modules`.`subProceso_has_extension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgd-modules`.`subProceso_has_extension` (
  `subProceso_idsubproceso` INT NOT NULL,
  `extension_idextension` INT NOT NULL,
  PRIMARY KEY (`subProceso_idsubproceso`, `extension_idextension`),
  INDEX `fk_subProceso_has_extension_extension1_idx` (`extension_idextension` ASC),
  INDEX `fk_subProceso_has_extension_subProceso1_idx` (`subProceso_idsubproceso` ASC),
  CONSTRAINT `fk_subProceso_has_extension_subProceso1`
    FOREIGN KEY (`subProceso_idsubproceso`)
    REFERENCES `sgd-modules`.`subProceso` (`idsubproceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subProceso_has_extension_extension1`
    FOREIGN KEY (`extension_idextension`)
    REFERENCES `sgd-modules`.`extension` (`idextension`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
